### ISSUE TITLE
If you can u do figure this  PROGRAMMING Read and understand the following code. Provide the correct input to have the program print the sentence: Exactly! Good Job.

### ISSUE THREAD

**Issue by obelr** [Tolulope05/alx-low_level_programming#1]
Before submitting your answer, please check its correctness by executing the code.
#include <stdio.h> 
#include <inttypes.h> 
#include <stdlib.h>
static int64_t ac_dc[] = { 14479, 12574, 54786, 51996, 77903, 16499 };
const static int N = sizeof(ac_dc)/sizeof(*ac_dc); 
static void fail(){
puts("Nope!"); 
exit(EXIT_FAILURE);
}
static void linkin_park(int64_t i, int64_t z, int64_t o){ 
if ( i - o / 7 + 3 * z / 11 )
fail();
}
static void the_beatles(int n, int64_t u){ 
int64_t s = u;
for(; n<N; ++n) {
if ((n % 2) == 0)
continue; 
s += ac_dc[n];
}
if (s != 159276)
fail();
}
static void metallica(int y, int64_t d){ 
if (y<N) {
if (y % 2)
metallica(++y, d);
else metallica(y + 1, d * ac_dc[y]);
} else if (d != 197887032) 
fail();
}
int main(){
int64_t r, l, h;
printf("Please enter the right three numbers: "); 
fflush(stdout);
if (scanf("%" SCNd64 " %" SCNd64 " %" SCNd64, &r, &l, &h) != 3) 
fail();
ac_dc[0] = r; 
ac_dc[5] = l; 
ac_dc[4] = h; 
the_beatles(0, 92627);
metallica(1, 3); 
linkin_park(r, l, h); 
puts("Exactly! Good job.");
}

**Comment by Tolulope05** [comment]
My programme Prints well..
Ensure you copy codes line by line so as to know whats going on instead of copying whole chunk of codes.
Thanks for your observation

**Comment by obelr** [comment]
Am sorry for putting chunk of codes that’s my bad 
And as the question what correct input (numbers )did u put to print “Exactly! Good job”
